name: Release Package

on:
  release:
    types: created

jobs:
  build-and-publish:
    name: Build & Publish Release Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Pack npm package
        id: pack
        run: |
          echo "Packing npm module..."
          PACKAGE_FILE=$(npm pack)
          echo "PACKAGE_FILE=$PACKAGE_FILE" >> $GITHUB_ENV

      - name: Upload install script to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: install.sh
          asset_name: install.sh
          asset_content_type: application/octet-stream

      - name: Determine repo name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Upload packaged project build to release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN:  ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: package.tar.gz
          asset_name: ${{ env.REPO_NAME }}-${{ github.event.release.tag_name }}.tar.gz
          asset_content_type: application/gzip
