name: Release Package

on:
  release:
    types: [published]

# ensure we can upload release assets
permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build & Publish Release Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Pack npm package
        id: pack
        run: |
          echo "Packing npm module..."
          PACKAGE_FILE=$(npm pack)
          echo "PACKAGE_FILE=$PACKAGE_FILE" >> $GITHUB_ENV

      - name: Upload install.sh as release asset
        uses: actions/upload-release-asset@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./install.sh
          asset_name: install.sh
          asset_content_type: application/x-sh

      - name: Upload npm package as release asset
        uses: actions/upload-release-asset@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.PACKAGE_FILE }}
          asset_name: ${{ env.PACKAGE_FILE }}
          asset_content_type: application/gzip
